//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ExamTerm
    {
        public ExamTerm()
        {
            this.ExamTypes = new HashSet<ExamType>();
        }
    
        public int Id { get; set; }
	[Required]
        public string TermName { get; set; }
	[Required]
        public Nullable<int> Percentage { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Year Year1 { get; set; }
        public virtual ICollection<ExamType> ExamTypes { get; set; }
    }
}
