//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityMarks = new HashSet<ActivityMark>();
        }
    
        public int Id { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsIncludedInResult { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Year Year1 { get; set; }
        public virtual ICollection<ActivityMark> ActivityMarks { get; set; }
    }
}
