//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityMark
    {
        public ActivityMark()
        {
            this.ActivityMarksDetails = new HashSet<ActivityMarksDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<int> ClassSectionId { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> PassPercentage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual ICollection<ActivityMarksDetail> ActivityMarksDetails { get; set; }
    }
}
