//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Activities = new HashSet<Activity>();
            this.Allownces = new HashSet<Allownce>();
            this.BankAccounts = new HashSet<BankAccount>();
            this.BehaviourCategories = new HashSet<BehaviourCategory>();
            this.Classes = new HashSet<Class>();
            this.DateSheets = new HashSet<DateSheet>();
            this.Designations = new HashSet<Designation>();
            this.DesignationCatagories = new HashSet<DesignationCatagory>();
            this.Exams = new HashSet<Exam>();
            this.ExamTerms = new HashSet<ExamTerm>();
            this.ExamTypes = new HashSet<ExamType>();
            this.FeeHeads = new HashSet<FeeHead>();
            this.FinanceFifthLvlAccounts = new HashSet<FinanceFifthLvlAccount>();
            this.FinanceFourthLvlAccounts = new HashSet<FinanceFourthLvlAccount>();
            this.FinanceThirdLvlAccounts = new HashSet<FinanceThirdLvlAccount>();
            this.Heads = new HashSet<Head>();
            this.RegisterCourses = new HashSet<RegisterCourse>();
            this.Sections = new HashSet<Section>();
            this.Sessions = new HashSet<Session>();
            this.Staffs = new HashSet<Staff>();
            this.StaffAttandancePolicies = new HashSet<StaffAttandancePolicy>();
            this.StaffBehaviourCategories = new HashSet<StaffBehaviourCategory>();
            this.Students = new HashSet<Student>();
            this.StudentInquiries = new HashSet<StudentInquiry>();
            this.Subjects = new HashSet<Subject>();
            this.TimeTables = new HashSet<TimeTable>();
            this.Users = new HashSet<User>();
            this.JournalEntries1 = new HashSet<JournalEntry>();
        }
    
        public int ID { get; set; }
        public string BRANCH_NAME { get; set; }
        public string BRANCH_CODE { get; set; }
        public string LOGIN_ID { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Allownce> Allownces { get; set; }
        public virtual ICollection<BankAccount> BankAccounts { get; set; }
        public virtual ICollection<BehaviourCategory> BehaviourCategories { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<DateSheet> DateSheets { get; set; }
        public virtual ICollection<Designation> Designations { get; set; }
        public virtual ICollection<DesignationCatagory> DesignationCatagories { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<ExamTerm> ExamTerms { get; set; }
        public virtual ICollection<ExamType> ExamTypes { get; set; }
        public virtual ICollection<FeeHead> FeeHeads { get; set; }
        public virtual ICollection<FinanceFifthLvlAccount> FinanceFifthLvlAccounts { get; set; }
        public virtual ICollection<FinanceFourthLvlAccount> FinanceFourthLvlAccounts { get; set; }
        public virtual ICollection<FinanceThirdLvlAccount> FinanceThirdLvlAccounts { get; set; }
        public virtual ICollection<Head> Heads { get; set; }
        public virtual ICollection<RegisterCourse> RegisterCourses { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<StaffAttandancePolicy> StaffAttandancePolicies { get; set; }
        public virtual ICollection<StaffBehaviourCategory> StaffBehaviourCategories { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentInquiry> StudentInquiries { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<TimeTable> TimeTables { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<JournalEntry> JournalEntries1 { get; set; }
    }
}
