//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanStudentDetail
    {
        public ChallanStudentDetail()
        {
            this.IssuedChallans = new HashSet<IssuedChallan>();
        }
    
        public int Id { get; set; }
        public int StdId { get; set; }
        public int ChallanId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Challan Challan { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<IssuedChallan> IssuedChallans { get; set; }
    }
}
