//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challan
    {
        public Challan()
        {
            this.ChallanFeeHeadDetails = new HashSet<ChallanFeeHeadDetail>();
            this.ChallanStudentDetails = new HashSet<ChallanStudentDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> SystemGenerated { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<ChallanFeeHeadDetail> ChallanFeeHeadDetails { get; set; }
        public virtual ICollection<ChallanStudentDetail> ChallanStudentDetails { get; set; }
    }
}
