//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanFeeHeadDetail
    {
        public int Id { get; set; }
        public int HeadId { get; set; }
        public int ChallanId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Challan Challan { get; set; }
        public virtual FeeHead FeeHead { get; set; }
    }
}
