//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Challans = new HashSet<Challan>();
            this.ClassSections = new HashSet<ClassSection>();
            this.StudentInquiries = new HashSet<StudentInquiry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsFinanceAccountOpen { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Challan> Challans { get; set; }
        public virtual ICollection<ClassSection> ClassSections { get; set; }
        public virtual ICollection<StudentInquiry> StudentInquiries { get; set; }
    }
}
