//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSection
    {
        public ClassSection()
        {
            this.ActivityMarks = new HashSet<ActivityMark>();
            this.DailyDairies = new HashSet<DailyDairy>();
            this.DailyTests = new HashSet<DailyTest>();
            this.Exams = new HashSet<Exam>();
            this.ExamPapers = new HashSet<ExamPaper>();
            this.RegisterCourses = new HashSet<RegisterCourse>();
            this.SessionSubjects = new HashSet<SessionSubject>();
            this.Students = new HashSet<Student>();
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public int ClassSectionId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool IsFinanceAccountOpen { get; set; }
    
        public virtual ICollection<ActivityMark> ActivityMarks { get; set; }
        public virtual Class Class { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<DailyDairy> DailyDairies { get; set; }
        public virtual ICollection<DailyTest> DailyTests { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<ExamPaper> ExamPapers { get; set; }
        public virtual ICollection<RegisterCourse> RegisterCourses { get; set; }
        public virtual ICollection<SessionSubject> SessionSubjects { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
