//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public Designation()
        {
            this.Staffs = new HashSet<Staff>();
            this.StaffAttandancePolicies = new HashSet<StaffAttandancePolicy>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CatagoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual DesignationCatagory DesignationCatagory { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<StaffAttandancePolicy> StaffAttandancePolicies { get; set; }
    }
}
