//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationCatagory
    {
        public DesignationCatagory()
        {
            this.Designations = new HashSet<Designation>();
        }
    
        public int Id { get; set; }
        public string CatagoryName { get; set; }
        public string CatagroryDescription { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Designation> Designations { get; set; }
    }
}
