//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamResult
    {
        public decimal id { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<decimal> ObtainedMarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
