//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.ExamResults = new HashSet<ExamResult>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ExamTypeId { get; set; }
        public Nullable<int> ClassSectionId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> PassPercentage { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
    }
}
