//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeBalance
    {
        public FeeBalance()
        {
            this.FeeArrearsDetails = new HashSet<FeeArrearsDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Advance { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<FeeArrearsDetail> FeeArrearsDetails { get; set; }
    }
}
