//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeHead
    {
        public FeeHead()
        {
            this.ChallanFeeHeadDetails = new HashSet<ChallanFeeHeadDetail>();
            this.FeeArrearsDetails = new HashSet<FeeArrearsDetail>();
            this.IssueChalanDetails = new HashSet<IssueChalanDetail>();
            this.StudentAdmissionCharges = new HashSet<StudentAdmissionCharge>();
            this.StudentExtraCharges = new HashSet<StudentExtraCharge>();
            this.StudentExtraChargesDetails = new HashSet<StudentExtraChargesDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<ChallanFeeHeadDetail> ChallanFeeHeadDetails { get; set; }
        public virtual ICollection<FeeArrearsDetail> FeeArrearsDetails { get; set; }
        public virtual ICollection<IssueChalanDetail> IssueChalanDetails { get; set; }
        public virtual ICollection<StudentAdmissionCharge> StudentAdmissionCharges { get; set; }
        public virtual ICollection<StudentExtraCharge> StudentExtraCharges { get; set; }
        public virtual ICollection<StudentExtraChargesDetail> StudentExtraChargesDetails { get; set; }
    }
}
