//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeIncrementHistory
    {
        public int IncrementId { get; set; }
        public string ClassId { get; set; }
        public string SectionId { get; set; }
        public Nullable<int> IncrementAmount { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
        public string IsDeleted { get; set; }
        public string Description { get; set; }
        public string FeeHead { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> PercentageIncrement { get; set; }
    }
}
