//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeIncrementHistoryDetail
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<int> GrossAmount { get; set; }
        public Nullable<bool> IsRevoked { get; set; }
        public string Description { get; set; }
        public Nullable<int> FeeHeadId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
