//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceSeccondLvlAccount
    {
        public FinanceSeccondLvlAccount()
        {
            this.FinanceThirdLvlAccounts = new HashSet<FinanceThirdLvlAccount>();
            this.JournalEntries2 = new HashSet<JournalEntry>();
            this.JournalEntries11 = new HashSet<JournalEntry>();
        }
    
        public int Id { get; set; }
        public int FirstLvlAccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Depreciation { get; set; }
    
        public virtual FinanceFirstLvlAccount FinanceFirstLvlAccount { get; set; }
        public virtual ICollection<FinanceThirdLvlAccount> FinanceThirdLvlAccounts { get; set; }
        public virtual ICollection<JournalEntry> JournalEntries2 { get; set; }
        public virtual ICollection<JournalEntry> JournalEntries11 { get; set; }
    }
}
