//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceFifthLvlAccount
    {
        public FinanceFifthLvlAccount()
        {
            this.JournalEntryCreditDetails = new HashSet<JournalEntryCreditDetail>();
            this.JournalEntryDebitDetails = new HashSet<JournalEntryDebitDetail>();
            this.StaffSalaries = new HashSet<StaffSalary>();
        }
    
        public int Id { get; set; }
        public int FourthLvlAccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<bool> IsPettyCashAccount { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual FinanceFourthLvlAccount FinanceFourthLvlAccount { get; set; }
        public virtual ICollection<JournalEntryCreditDetail> JournalEntryCreditDetails { get; set; }
        public virtual ICollection<JournalEntryDebitDetail> JournalEntryDebitDetails { get; set; }
        public virtual ICollection<StaffSalary> StaffSalaries { get; set; }
    }
}
