//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceFirstLvlAccount
    {
        public FinanceFirstLvlAccount()
        {
            this.FinanceSeccondLvlAccounts = new HashSet<FinanceSeccondLvlAccount>();
            this.JournalEntries1 = new HashSet<JournalEntry>();
        }
    
        public int Id { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<FinanceSeccondLvlAccount> FinanceSeccondLvlAccounts { get; set; }
        public virtual ICollection<JournalEntry> JournalEntries1 { get; set; }
    }
}
