//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueChalanDetail
    {
        public int ID { get; set; }
        public Nullable<decimal> IssueChallanId { get; set; }
        public Nullable<int> FeeHeadId { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> PayAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual FeeHead FeeHead { get; set; }
        public virtual IssuedChallan IssuedChallan { get; set; }
    }
}
