//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedChallan
    {
        public IssuedChallan()
        {
            this.IssueChalanDetails = new HashSet<IssueChalanDetail>();
        }
    
        public decimal Id { get; set; }
        public Nullable<int> ChallanToStdId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> PaidFlag { get; set; }
        public string ForMonth { get; set; }
        public Nullable<int> Fine { get; set; }
        public Nullable<int> PayedTo { get; set; }
        public Nullable<int> IssuedFlag { get; set; }
        public Nullable<int> ChalanAmount { get; set; }
        public Nullable<int> PayedToType { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> IsLcm { get; set; }
    
        public virtual ChallanStudentDetail ChallanStudentDetail { get; set; }
        public virtual ICollection<IssueChalanDetail> IssueChalanDetails { get; set; }
    }
}
