//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPurchaseDetail
    {
        public int Id { get; set; }
        public Nullable<int> ItemPurchaseId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> IssuanceQuantity { get; set; }
    
        public virtual ItemPurchase ItemPurchase { get; set; }
        public virtual Item Item { get; set; }
    }
}
