//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemIssuanceDetails = new HashSet<ItemIssuanceDetail>();
            this.ItemPurchaseDetails = new HashSet<ItemPurchaseDetail>();
            this.ItemReturnDetails = new HashSet<ItemReturnDetail>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<ItemIssuanceDetail> ItemIssuanceDetails { get; set; }
        public virtual ICollection<ItemPurchaseDetail> ItemPurchaseDetails { get; set; }
        public virtual ICollection<ItemReturnDetail> ItemReturnDetails { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
    }
}
