//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public JournalEntry()
        {
            this.JournalEntryCreditDetails = new HashSet<JournalEntryCreditDetail>();
            this.JournalEntryDebitDetails = new HashSet<JournalEntryDebitDetail>();
            this.JournalVouchers = new HashSet<JournalVoucher>();
        }
    
        public int EntryId { get; set; }
        public Nullable<int> DebitFirstLvlId { get; set; }
        public Nullable<int> DebitSeccondLvlId { get; set; }
        public Nullable<int> DebitAmount { get; set; }
        public Nullable<int> CreditFirstLvlId { get; set; }
        public Nullable<int> CreditSeccondLvlId { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreditDescription { get; set; }
        public string DebitDescription { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<int> DebitThirdLvlId { get; set; }
        public Nullable<int> DebitFourthLvlId { get; set; }
        public Nullable<int> CreditThirdLvlId { get; set; }
        public Nullable<int> CreditFourthLvlId { get; set; }
        public Nullable<int> CreditFifthLvlId { get; set; }
        public string ChequeNo { get; set; }
        public string EntryType { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string LongDescription { get; set; }
        public Nullable<bool> SystemGenerated { get; set; }
        public Nullable<bool> IsPettyCash { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual FinanceFirstLvlAccount FinanceFirstLvlAccount { get; set; }
        public virtual FinanceFourthLvlAccount FinanceFourthLvlAccount { get; set; }
        public virtual FinanceFourthLvlAccount FinanceFourthLvlAccount1 { get; set; }
        public virtual FinanceSeccondLvlAccount FinanceSeccondLvlAccount { get; set; }
        public virtual FinanceSeccondLvlAccount FinanceSeccondLvlAccount1 { get; set; }
        public virtual FinanceThirdLvlAccount FinanceThirdLvlAccount { get; set; }
        public virtual FinanceThirdLvlAccount FinanceThirdLvlAccount1 { get; set; }
        public virtual ICollection<JournalEntryCreditDetail> JournalEntryCreditDetails { get; set; }
        public virtual ICollection<JournalEntryDebitDetail> JournalEntryDebitDetails { get; set; }
        public virtual ICollection<JournalVoucher> JournalVouchers { get; set; }
    }
}
