//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntrySummary
    {
        public int EntryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string DebitAccount { get; set; }
        public Nullable<int> DebitAmount { get; set; }
        public string DebitDescription { get; set; }
        public string CreditAccount { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public string CreditDecription { get; set; }
        public string ChequeNo { get; set; }
        public string SubHeadType { get; set; }
    }
}
