//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavingReason
    {
        public LeavingReason()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int ReasonId { get; set; }
        public string LeavingReason1 { get; set; }
    
        public virtual LeavingReason LeavingReason11 { get; set; }
        public virtual LeavingReason LeavingReason2 { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
