//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.PaymentHistories = new HashSet<PaymentHistory>();
        }
    
        public int TypeId { get; set; }
        public string PaymentName { get; set; }
    
        public virtual ICollection<PaymentHistory> PaymentHistories { get; set; }
    }
}
