//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public int ID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> IssueChallanId { get; set; }
        public Nullable<int> FeeBalanceId { get; set; }
        public Nullable<int> FeeHeadId { get; set; }
        public Nullable<int> PayAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Description { get; set; }
        public Nullable<int> FeeType { get; set; }
        public string ForMonth { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> PayedTo { get; set; }
        public Nullable<int> PayedToType { get; set; }
    
        public virtual PaymentType PaymentType1 { get; set; }
    }
}
