//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousGrade
    {
        public int Student_Id { get; set; }
        public int Class_Id { get; set; }
        public int Section_Id { get; set; }
        public string Year { get; set; }
        public int Id { get; set; }
    }
}
