//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relegion
    {
        public Relegion()
        {
            this.Staffs = new HashSet<Staff>();
            this.Students = new HashSet<Student>();
            this.StudentInquiries = new HashSet<StudentInquiry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<StudentInquiry> StudentInquiries { get; set; }
    }
}
