//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public int REPORT_ID { get; set; }
        public string REPORT_NAME { get; set; }
        public Nullable<int> MODULE_ID { get; set; }
    }
}
