//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolConfig
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string CampusName { get; set; }
        public byte[] SchoolLogo { get; set; }
        public byte[] CardImage { get; set; }
        public Nullable<int> BranchId { get; set; }
        public byte[] PrincipalSignature { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
    }
}
