//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionSubject
    {
        public int Id { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> ClassSectionId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<System.DateTime> From_Date { get; set; }
        public Nullable<System.DateTime> To_Date { get; set; }
        public string SessionYear { get; set; }
    
        public virtual ClassSection ClassSection { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
