//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionUser
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<System.DateTime> LOGIN_TIME { get; set; }
        public Nullable<System.DateTime> LOGOUT_TIME { get; set; }
        public Nullable<int> LOGIN_STATUS { get; set; }
    
        public virtual User User { get; set; }
    }
}
