//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsEvent
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public bool SmsFlag { get; set; }
        public Nullable<int> SmsTemplateId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string EventDetail { get; set; }
    
        public virtual SmsMessage SmsMessage { get; set; }
    }
}
