//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsMessage
    {
        public SmsMessage()
        {
            this.SmsEvents = new HashSet<SmsEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual ICollection<SmsEvent> SmsEvents { get; set; }
    }
}
