//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffBehaviour
    {
        public int ID { get; set; }
        public string Comment { get; set; }
        public double Rating { get; set; }
        public int StaffId { get; set; }
        public int ParameterId { get; set; }
        public int EvaluatingStaffId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public double ParameterRating { get; set; }
        public double RatingWeightage { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual StaffBehaviourParameter StaffBehaviourParameter { get; set; }
    }
}
