//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAllownce
    {
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> AllownceId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Increment { get; set; }
    
        public virtual Allownce Allownce { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
