//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAttandance
    {
        public StaffAttandance()
        {
            this.StaffAttendanceDetails = new HashSet<StaffAttendanceDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string OutTime { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StudentAttendanceStatu StudentAttendanceStatu { get; set; }
        public virtual ICollection<StaffAttendanceDetail> StaffAttendanceDetails { get; set; }
    }
}
