//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSalaryIncrementHistory
    {
        public int IncrementId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> IncrementType { get; set; }
        public Nullable<int> Increment { get; set; }
        public Nullable<int> AllownceType { get; set; }
        public Nullable<int> AllownceId { get; set; }
        public Nullable<bool> IsApplied { get; set; }
        public Nullable<System.DateTime> IncrementDate { get; set; }
        public string Description { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
