//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDegree
    {
        public int Id { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string DegreeName { get; set; }
        public string Year { get; set; }
        public Nullable<int> ObtMarks { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public string RollNo { get; set; }
        public string Institute { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
