//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAttendanceRequestDetail
    {
        public int Id { get; set; }
        public Nullable<int> StaffAttendanceRequestId { get; set; }
        public Nullable<int> AttendanceId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Comments { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string AttendanceInTime { get; set; }
        public string AttendanceOutTime { get; set; }
        public Nullable<int> AttendanceStatusId { get; set; }
    
        public virtual StaffAttendanceRequest StaffAttendanceRequest { get; set; }
    }
}
