//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffBehaviourParameter
    {
        public StaffBehaviourParameter()
        {
            this.StaffBehaviours = new HashSet<StaffBehaviour>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Rating { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<StaffBehaviour> StaffBehaviours { get; set; }
        public virtual StaffBehaviourCategory StaffBehaviourCategory { get; set; }
    }
}
