//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExtraCharge
    {
        public StudentExtraCharge()
        {
            this.StudentExtraChargesDetails = new HashSet<StudentExtraChargesDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FeeHeadId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> HeadAmount { get; set; }
        public string ForMonth { get; set; }
        public string RollNumber { get; set; }
        public string Criteria { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual FeeHead FeeHead { get; set; }
        public virtual ICollection<StudentExtraChargesDetail> StudentExtraChargesDetails { get; set; }
    }
}
