//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendanceStatu
    {
        public StudentAttendanceStatu()
        {
            this.Attandances = new HashSet<Attandance>();
            this.StaffAttandances = new HashSet<StaffAttandance>();
        }
    
        public int Id { get; set; }
        public string CodeName { get; set; }
    
        public virtual ICollection<Attandance> Attandances { get; set; }
        public virtual ICollection<StaffAttandance> StaffAttandances { get; set; }
    }
}
