//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.AnnualCharges = new HashSet<AnnualCharge>();
            this.Attandances = new HashSet<Attandance>();
            this.ChallanStudentDetails = new HashSet<ChallanStudentDetail>();
            this.ExamResults = new HashSet<ExamResult>();
            this.PreviousStudyHistories = new HashSet<PreviousStudyHistory>();
            this.SACPaidCatalogs = new HashSet<SACPaidCatalog>();
            this.StudentAdmissionCharges = new HashSet<StudentAdmissionCharge>();
            this.StudentBehaviours = new HashSet<StudentBehaviour>();
            this.StudentDocuments = new HashSet<StudentDocument>();
        }
    
        public int id { get; set; }
        public string RollNumber { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string Contact_1 { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<int> ReligionCode { get; set; }
        public Nullable<int> GenderCode { get; set; }
        public string ImageLocation { get; set; }
        public string SrNo { get; set; }
        public string FatherOccupation { get; set; }
        public string Nationality { get; set; }
        public string Cast { get; set; }
        public string FatherCNIC { get; set; }
        public string Contact_2 { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public string SessionYear { get; set; }
        public string MotherName { get; set; }
        public string MotherContact1 { get; set; }
        public string MotherContact2 { get; set; }
        public bool ChildPictures { get; set; }
        public bool CNIC { get; set; }
        public bool BirthCertificate { get; set; }
        public bool SchoolLeaving { get; set; }
        public string Email { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public string PreviousCampus { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public bool ClearDues { get; set; }
        public byte[] StdImage { get; set; }
        public Nullable<int> ClassSectionId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string BFormNo { get; set; }
        public string WithDrawalClass { get; set; }
        public string StudyDuration { get; set; }
        public string MotherCnic { get; set; }
        public string MotherOccupation { get; set; }
        public bool IsMotherCnic { get; set; }
        public Nullable<int> LeavingStatus { get; set; }
        public string LeavingRemarks { get; set; }
        public string InquiryNo { get; set; }
        public Nullable<int> FinanceAccountId { get; set; }
        public string AdmissionIncharge { get; set; }
        public string GuardianName { get; set; }
        public string GuardinCnic { get; set; }
        public string GuardinContact { get; set; }
        public string FatherWorkplace { get; set; }
        public string MotherWorkplace { get; set; }
        public string SeriousIllness { get; set; }
        public string PhysicalDisability { get; set; }
        public string LearningDiability { get; set; }
        public bool IsDeclarationBirth { get; set; }
        public bool IsEmergencyInformation { get; set; }
        public bool IsPhysicalLikeness { get; set; }
        public bool IsMedicalProcedure { get; set; }
        public bool IsVaccination { get; set; }
        public bool IsNadraBformNo { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string AdmissionNo { get; set; }
        public bool IsEVS { get; set; }
        public Nullable<int> VanFee { get; set; }
        public string StopName { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<bool> IsPromoted { get; set; }
    
        public virtual AdmissionType AdmissionType1 { get; set; }
        public virtual ICollection<AnnualCharge> AnnualCharges { get; set; }
        public virtual ICollection<Attandance> Attandances { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual ICollection<ChallanStudentDetail> ChallanStudentDetails { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual LeavingReason LeavingReason { get; set; }
        public virtual LeavingStatu LeavingStatu { get; set; }
        public virtual ICollection<PreviousStudyHistory> PreviousStudyHistories { get; set; }
        public virtual Relegion Relegion { get; set; }
        public virtual ICollection<SACPaidCatalog> SACPaidCatalogs { get; set; }
        public virtual Session Session { get; set; }
        public virtual ICollection<StudentAdmissionCharge> StudentAdmissionCharges { get; set; }
        public virtual ICollection<StudentBehaviour> StudentBehaviours { get; set; }
        public virtual ICollection<StudentDocument> StudentDocuments { get; set; }
    }
}
