//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExtraChargesDetail
    {
        public int ID { get; set; }
        public Nullable<int> ExtraChargesId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> HeadId { get; set; }
        public Nullable<int> HeadAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ForMonth { get; set; }
    
        public virtual FeeHead FeeHead { get; set; }
        public virtual StudentExtraCharge StudentExtraCharge { get; set; }
    }
}
