//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.DailyTests = new HashSet<DailyTest>();
            this.DateSheets = new HashSet<DateSheet>();
            this.Exams = new HashSet<Exam>();
            this.ExamPapers = new HashSet<ExamPaper>();
            this.RegisterCourses = new HashSet<RegisterCourse>();
            this.SessionSubjects = new HashSet<SessionSubject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<DailyTest> DailyTests { get; set; }
        public virtual ICollection<DateSheet> DateSheets { get; set; }
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual ICollection<ExamPaper> ExamPapers { get; set; }
        public virtual ICollection<RegisterCourse> RegisterCourses { get; set; }
        public virtual ICollection<SessionSubject> SessionSubjects { get; set; }
    }
}
