//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectChapter
    {
        public SubjectChapter()
        {
            this.ChapterTopics = new HashSet<ChapterTopic>();
            this.TermChapters = new HashSet<TermChapter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int RegisterCourseId { get; set; }
        public bool IsCovered { get; set; }
    
        public virtual ICollection<ChapterTopic> ChapterTopics { get; set; }
        public virtual RegisterCourse RegisterCourse { get; set; }
        public virtual ICollection<TermChapter> TermChapters { get; set; }
    }
}
