//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermChapter
    {
        public int Id { get; set; }
        public Nullable<int> ChapterId { get; set; }
        public Nullable<int> TermId { get; set; }
    
        public virtual ExamTerm ExamTerm { get; set; }
        public virtual SubjectChapter SubjectChapter { get; set; }
    }
}
