//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int ID { get; set; }
        public int BranchId { get; set; }
        public int TeacherId { get; set; }
        public int ClassSubjectId { get; set; }
        public int ClassSectionId { get; set; }
        public int Day { get; set; }
        public int Slot { get; set; }
        public int RoomId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ClassSection ClassSection { get; set; }
        public virtual RegisterCourse RegisterCourse { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
