//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportDriver
    {
        public int Id { get; set; }
        public string VanNo { get; set; }
        public string DriverName { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
