//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SessionUsers = new HashSet<SessionUser>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LoginId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<SessionUser> SessionUsers { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual User Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
