//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.GroupPermissions = new HashSet<GroupPermission>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual ICollection<GroupPermission> GroupPermissions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
